const THUMBNAIL_PADDING = 2;
const MAX_THUMBNAILS_HEIGHT = 70 + THUMBNAIL_PADDING * 2;
const MIN_DISTANCE_DELTA = 5;

const TABLET_BREAKEPOINT = 740;

const DIRECTION_BACKWARD = Symbol();
const DIRECTION_FORWARD = Symbol();

export default {
  DIRECTION_BACKWARD,
  DIRECTION_FORWARD,
  MAX_THUMBNAILS_HEIGHT,
  MIN_DISTANCE_DELTA,
  TABLET_BREAKEPOINT,
  THUMBNAIL_PADDING
}
