const THUMBNAIL_HEIGHT = 70;
const THUMBNAIL_PADDING_HORIZONTAL = 2.5;
const MIN_DISTANCE_DELTA = 5;

const TABLET_BREAKEPOINT = 740;

const DIRECTION_BACKWARD = Symbol('Backward');
const DIRECTION_FORWARD = Symbol('Forward');

export default {
  DIRECTION_BACKWARD,
  DIRECTION_FORWARD,
  MIN_DISTANCE_DELTA,
  TABLET_BREAKEPOINT,
  THUMBNAIL_HEIGHT,
  THUMBNAIL_PADDING_HORIZONTAL
}
